name: ci-environment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - statsmodels
  - geopandas
  - shapely
  - osmnx
  - networkx
  - dask
  - pyarrow
  - pip
  - pip:
      - pytest
      - flake8
<<<<<<< HEAD
=======
      - package_name_not_in_conda
>>>>>>> 48b1e10b4bc5007ca25bb67f37c8a37e9f095547
