name: ci-environment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=1.26.4
  - pandas=2.2.2
  - scikit-learn=1.5.2
  - scipy=1.13.1
  - statsmodels=0.14.2
  - matplotlib>=3.8,<3.10
  - geopandas=0.14.3
  - shapely=2.0.4
  - osmnx=1.9.4
  - networkx=3.2.1
  - dask=2024.5.1
  - pyarrow=14.0.2
  - pip
  - pip:
      - pymc==5.15.1
      - arviz==0.18.0
      - pytest==7.4.0
      - flake8==6.1.0
      - black==24.8.0
      - jupyterlab==4.2.4
      - notebook==6.5.4
          
