name: Python Package (Conda)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Cache Conda packages
      - name: Cache Conda
        uses: actions/cache@v4
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ hashFiles('environment.yml') }}
          restore-keys: |
            ${{ runner.os }}-conda-

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: base
          environment-file: environment.yml
          python-version: 3.10
          auto-update-conda: true
          channels: conda-forge, defaults
          use-only-tar-bz2: true

      - name: Verify environment
        run: conda list
        working-directory: ./TSAS_Special_Issue_Urban_Mobility

      - name: Lint with flake8
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        working-directory: ./TSAS_Special_Issue_Urban_Mobility

      - name: Run tests with pytest
        run: pytest
        working-directory: ./TSAS_Special_Issue_Urban_Mobility
